// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA1lcmMeS_GOlRh07ku5EZitsPagV_JIU',
    appId: '1:233453377047:web:7e6d9022a59767f083ee52',
    messagingSenderId: '233453377047',
    projectId: 'readrss-88285',
    authDomain: 'readrss-88285.firebaseapp.com',
    storageBucket: 'readrss-88285.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEBM0FYNy0bATs8l-m7BHfpMtoy_zlwfQ',
    appId: '1:233453377047:android:c0d99985e0f341f983ee52',
    messagingSenderId: '233453377047',
    projectId: 'readrss-88285',
    storageBucket: 'readrss-88285.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuXMM-pESP-hvqE3QjkD0TeNl37dfK4zM',
    appId: '1:233453377047:ios:7bbcdd5019ace4a183ee52',
    messagingSenderId: '233453377047',
    projectId: 'readrss-88285',
    storageBucket: 'readrss-88285.appspot.com',
    iosBundleId: 'com.example.flutterReadrss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuXMM-pESP-hvqE3QjkD0TeNl37dfK4zM',
    appId: '1:233453377047:ios:f5042b7655214e4b83ee52',
    messagingSenderId: '233453377047',
    projectId: 'readrss-88285',
    storageBucket: 'readrss-88285.appspot.com',
    iosBundleId: 'com.example.flutterReadrss.RunnerTests',
  );
}
