// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbWNxklAEtMj7-2avXsx5A94MwOPKlmQw',
    appId: '1:685835080260:android:0744152b731f9bcd8fe211',
    messagingSenderId: '685835080260',
    projectId: 'flutter-readrss',
    storageBucket: 'flutter-readrss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN7GttX-4LpU59CNKtCszj994qhaI2_Ok',
    appId: '1:685835080260:ios:e9b9fd19da3c0b8e8fe211',
    messagingSenderId: '685835080260',
    projectId: 'flutter-readrss',
    storageBucket: 'flutter-readrss.appspot.com',
    iosBundleId: 'com.example.flutterReadrss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN7GttX-4LpU59CNKtCszj994qhaI2_Ok',
    appId: '1:685835080260:ios:11908ca8f12f4f398fe211',
    messagingSenderId: '685835080260',
    projectId: 'flutter-readrss',
    storageBucket: 'flutter-readrss.appspot.com',
    iosBundleId: 'com.example.flutterReadrss.RunnerTests',
  );
}
